version: "3.7"

networks:
  backend:
    
services:
      
  flexibleschedule:
    image: tb
    build:
      context: .
      dockerfile: /Users/danilalatyrev/Desktop/ForProjects/FlexibleSchedule/FlexibleSchedule/Dockerfile
    ports:
      - "8001:80"
    depends_on: 
      - db
    networks:
      - backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: lfybk2000
      MYSQL_DB: FlexibleSchedule
    container_name: backich
  db:
    networks:
      - backend
    ports:
      - "8002:3306"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lfybk2000
      MYSQL_DATABASE: FlexibleSchedule
    container_name: db_

    
